# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

default: &default
  # adapter: sqlite3
  # pool: 5
  # timeout: 5000
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  database: barnburger_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: barnburger_test
  pool: 5
  username: postgres
  password: postgres

production:
  <<: *default
  database: barnburger_production
  username: barnburger
  password: <%= ENV['BARNBURGER_DATABASE_PASSWORD'] %>
