# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

test:
  # adapter: sqlite3
  # pool: 5
  # timeout: 5000
  adapter: postgresql
  encoding: unicode
  database: barnburger_development
  pool: 5
  username: postgres
  password: postgres

development:
  adapter: postgresql
  encoding: unicode
  database: barnburger_development
  pool: 5
  username: postgres
  password: postgres


# production:
#   adapter: postgresql
#   encoding: unicode
#   database: barnburger_prod
#   pool: 5
#   username: postgres
#   password: postgres